apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: custom-route-table
  namespace: apps-portal
spec:
  routes:
  - name: findPetsWithHeaderMatch
    matchers:
    - exact: /api/pets
      methods:
      - GET
      - OPTIONS
      headers:
      - name: x-custom-header
        value: teapot
    routeAction:
      multi:
        destinations:
        - destination:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
          weight: 1
  - matchers:
    - exact: /api/pets
      methods:
      - GET
      - OPTIONS
    name: petstore-product.apps-portal.petstore-schema.apps-portal.findPets
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - matcher:
              prefix: /
            requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: environment
                  value:
                    text: dev.apps-portal
                - key: api_product
                  value:
                    text: petstore-product.apps-portal
                passthrough: {}
    routeAction:
      multi:
        destinations:
        - destination:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
          weight: 1
  - matchers:
    - exact: /api/pets
      methods:
      - POST
      - OPTIONS
    name: petstore-product.apps-portal.petstore-schema.apps-portal.addPet
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - matcher:
              prefix: /
            requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: environment
                  value:
                    text: dev.apps-portal
                - key: api_product
                  value:
                    text: petstore-product.apps-portal
                passthrough: {}
    routeAction:
      multi:
        destinations:
        - destination:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
          weight: 1
  - matchers:
    - methods:
      - DELETE
      - OPTIONS
      regex: /api/pets/[^/]+?
    name: petstore-product.apps-portal.petstore-schema.apps-portal.deletePet
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - matcher:
              prefix: /
            requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: environment
                  value:
                    text: dev.apps-portal
                - key: api_product
                  value:
                    text: petstore-product.apps-portal
                passthrough: {}
    routeAction:
      multi:
        destinations:
        - destination:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
          weight: 1
  - matchers:
    - methods:
      - GET
      - OPTIONS
      regex: /api/pets/[^/]+?
    name: petstore-product.apps-portal.petstore-schema.apps-portal.findPetById
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - matcher:
              prefix: /
            requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: environment
                  value:
                    text: dev.apps-portal
                - key: api_product
                  value:
                    text: petstore-product.apps-portal
                passthrough: {}
    routeAction:
      multi:
        destinations:
        - destination:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
          weight: 1
